(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "__FILE__" "__LINE__" "__PACKAGE__" "__SUB__"
"abs" "accept" "alarm" "atan2" "bind" "binmode" "bless" "break" "caller"
"chdir" "chmod" "chomp" "chop" "chown" "chr" "chroot" "close" "closedir"
"connect" "continue" "cos" "crypt" "dbmclose" "dbmopen" "defined" "delete"
"die" "do" "dump" "each" "endgrent" "endhostent" "endnetent" "endprotoent"
"endpwent" "endservent" "eof" "eval" "evalbytes" "exec" "exists" "exit"
"exp" "fc" "fcntl" "fileno" "flock" "fork" "format" "formline" "getc"
"getgrent" "getgrgid" "getgrnam" "gethostbyaddr" "gethostbyname"
"gethostent" "getlogin" "getnetbyaddr" "getnetbyname" "getnetent"
"getpeername" "getpgrp" "getppid" "getpriority" "getprotobyname"
"getprotobynumber" "getprotoent" "getpwent" "getpwnam" "getpwuid"
"getservbyname" "getservbyport" "getservent" "getsockname" "getsockopt"
"glob" "gmtime" "goto" "grep" "hex" "import" "index" "int" "ioctl" "join"
"keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen" "local"
"localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl" "msgget"
"msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord" "our"
"pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype" "push" "q"
"qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir" "readline"
"readlink" "readpipe" "recv" "redo" "ref" "rename" "require" "reset"
"return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar" "seek"
"seekdir" "select" "semctl" "semget" "semop" "send" "setgrent" "sethostent"
"setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent" "setservent"
"setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite" "shutdown"
"sin" "sleep" "socket" "socketpair" "sort" "splice" "split" "sprintf"
"sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink" "syscall"
"sysopen" "sysread" "sysseek" "system" "syswrite" "tell" "telldir" "tie"
"tied" "time" "times" "tr" "truncate" "uc" "ucfirst" "umask" "undef"
"unlink" "unpack" "unshift" "untie" "use" "utime" "values" "vec" "wait"
"waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AnyDBM_File" "App::Cpan" "App::Prove" "App::Prove::State"
"App::Prove::State::Result" "App::Prove::State::Result::Test" "AppConfig"
"AppConfig::Args" "AppConfig::CGI" "AppConfig::File" "AppConfig::Getopt"
"AppConfig::State" "AppConfig::Sys" "Archive::Extract" "Archive::Tar"
"Archive::Tar::Constant" "Archive::Tar::File" "Attribute::Handlers"
"AutoLoader" "AutoSplit" "B" "B::Concise" "B::Debug" "B::Deparse" "B::Lint"
"B::Lint::Debug" "B::Showlex" "B::Terse" "B::Xref" "Benchmark" "CGI"
"CGI::Apache" "CGI::Carp" "CGI::Cookie" "CGI::Fast" "CGI::Pretty"
"CGI::Push" "CGI::Switch" "CGI::Util" "CPAN" "CPAN::Author" "CPAN::Bundle"
"CPAN::CacheMgr" "CPAN::Complete" "CPAN::Debug" "CPAN::DeferredCode"
"CPAN::Distribution" "CPAN::Distroprefs" "CPAN::Distrostatus"
"CPAN::Exception::RecursiveDependency" "CPAN::Exception::blocked_urllist"
"CPAN::Exception::yaml_not_installed" "CPAN::Exception::yaml_process_error"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HTTP::Client"
"CPAN::HTTP::Credentials" "CPAN::HandleConfig" "CPAN::Index"
"CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Meta"
"CPAN::Meta::Converter" "CPAN::Meta::Feature" "CPAN::Meta::History"
"CPAN::Meta::Prereqs" "CPAN::Meta::Requirements" "CPAN::Meta::Spec"
"CPAN::Meta::Validator" "CPAN::Meta::YAML" "CPAN::Mirrors" "CPAN::Module"
"CPAN::Nox" "CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip"
"CPAN::URL" "CPAN::Version" "CPANPLUS" "CPANPLUS::Backend"
"CPANPLUS::Backend::RV" "CPANPLUS::Config" "CPANPLUS::Configure"
"CPANPLUS::Configure::Setup" "CPANPLUS::Dist" "CPANPLUS::Dist::Autobundle"
"CPANPLUS::Dist::Base" "CPANPLUS::Dist::Build"
"CPANPLUS::Dist::Build::Constants" "CPANPLUS::Dist::MM"
"CPANPLUS::Dist::Sample" "CPANPLUS::Error" "CPANPLUS::Internals"
"CPANPLUS::Internals::Constants" "CPANPLUS::Internals::Constants::Report"
"CPANPLUS::Internals::Extract" "CPANPLUS::Internals::Fetch"
"CPANPLUS::Internals::Report" "CPANPLUS::Internals::Search"
"CPANPLUS::Internals::Source" "CPANPLUS::Internals::Source::Memory"
"CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Carp" "Carp::Heavy"
"Class::Struct" "Compress::Raw::Bzip2" "Compress::Raw::Zlib"
"Compress::Zlib" "Config" "Config::Extensions" "Cwd" "DB" "DBM_Filter"
"DBM_Filter::compress" "DBM_Filter::encode" "DBM_Filter::int32"
"DBM_Filter::null" "DBM_Filter::utf8" "DB_File" "Data::Dumper"
"Date::Manip" "Date::Manip::Base" "Date::Manip::DM5"
"Date::Manip::DM5abbrevs" "Date::Manip::DM6" "Date::Manip::Date"
"Date::Manip::Delta" "Date::Manip::Lang::catalan"
"Date::Manip::Lang::danish" "Date::Manip::Lang::dutch"
"Date::Manip::Lang::english" "Date::Manip::Lang::finnish"
"Date::Manip::Lang::french" "Date::Manip::Lang::german"
"Date::Manip::Lang::index" "Date::Manip::Lang::italian"
"Date::Manip::Lang::norwegian" "Date::Manip::Lang::polish"
"Date::Manip::Lang::portugue" "Date::Manip::Lang::romanian"
"Date::Manip::Lang::russian" "Date::Manip::Lang::spanish"
"Date::Manip::Lang::swedish" "Date::Manip::Lang::turkish"
"Date::Manip::Obj" "Date::Manip::Offset::off000"
"Date::Manip::Offset::off001" "Date::Manip::Offset::off002"
"Date::Manip::Offset::off003" "Date::Manip::Offset::off004"
"Date::Manip::Offset::off005" "Date::Manip::Offset::off006"
"Date::Manip::Offset::off007" "Date::Manip::Offset::off008"
"Date::Manip::Offset::off009" "Date::Manip::Offset::off010"
"Date::Manip::Offset::off011" "Date::Manip::Offset::off012"
"Date::Manip::Offset::off013" "Date::Manip::Offset::off014"
"Date::Manip::Offset::off015" "Date::Manip::Offset::off016"
"Date::Manip::Offset::off017" "Date::Manip::Offset::off018"
"Date::Manip::Offset::off019" "Date::Manip::Offset::off020"
"Date::Manip::Offset::off021" "Date::Manip::Offset::off022"
"Date::Manip::Offset::off023" "Date::Manip::Offset::off024"
"Date::Manip::Offset::off025" "Date::Manip::Offset::off026"
"Date::Manip::Offset::off027" "Date::Manip::Offset::off028"
"Date::Manip::Offset::off029" "Date::Manip::Offset::off030"
"Date::Manip::Offset::off031" "Date::Manip::Offset::off032"
"Date::Manip::Offset::off033" "Date::Manip::Offset::off034"
"Date::Manip::Offset::off035" "Date::Manip::Offset::off036"
"Date::Manip::Offset::off037" "Date::Manip::Offset::off038"
"Date::Manip::Offset::off039" "Date::Manip::Offset::off040"
"Date::Manip::Offset::off041" "Date::Manip::Offset::off042"
"Date::Manip::Offset::off043" "Date::Manip::Offset::off044"
"Date::Manip::Offset::off045" "Date::Manip::Offset::off046"
"Date::Manip::Offset::off047" "Date::Manip::Offset::off048"
"Date::Manip::Offset::off049" "Date::Manip::Offset::off050"
"Date::Manip::Offset::off051" "Date::Manip::Offset::off052"
"Date::Manip::Offset::off053" "Date::Manip::Offset::off054"
"Date::Manip::Offset::off055" "Date::Manip::Offset::off056"
"Date::Manip::Offset::off057" "Date::Manip::Offset::off058"
"Date::Manip::Offset::off059" "Date::Manip::Offset::off060"
"Date::Manip::Offset::off061" "Date::Manip::Offset::off062"
"Date::Manip::Offset::off063" "Date::Manip::Offset::off064"
"Date::Manip::Offset::off065" "Date::Manip::Offset::off066"
"Date::Manip::Offset::off067" "Date::Manip::Offset::off068"
"Date::Manip::Offset::off069" "Date::Manip::Offset::off070"
"Date::Manip::Offset::off071" "Date::Manip::Offset::off072"
"Date::Manip::Offset::off073" "Date::Manip::Offset::off074"
"Date::Manip::Offset::off075" "Date::Manip::Offset::off076"
"Date::Manip::Offset::off077" "Date::Manip::Offset::off078"
"Date::Manip::Offset::off079" "Date::Manip::Offset::off080"
"Date::Manip::Offset::off081" "Date::Manip::Offset::off082"
"Date::Manip::Offset::off083" "Date::Manip::Offset::off084"
"Date::Manip::Offset::off085" "Date::Manip::Offset::off086"
"Date::Manip::Offset::off087" "Date::Manip::Offset::off088"
"Date::Manip::Offset::off089" "Date::Manip::Offset::off090"
"Date::Manip::Offset::off091" "Date::Manip::Offset::off092"
"Date::Manip::Offset::off093" "Date::Manip::Offset::off094"
"Date::Manip::Offset::off095" "Date::Manip::Offset::off096"
"Date::Manip::Offset::off097" "Date::Manip::Offset::off098"
"Date::Manip::Offset::off099" "Date::Manip::Offset::off100"
"Date::Manip::Offset::off101" "Date::Manip::Offset::off102"
"Date::Manip::Offset::off103" "Date::Manip::Offset::off104"
"Date::Manip::Offset::off105" "Date::Manip::Offset::off106"
"Date::Manip::Offset::off107" "Date::Manip::Offset::off108"
"Date::Manip::Offset::off109" "Date::Manip::Offset::off110"
"Date::Manip::Offset::off111" "Date::Manip::Offset::off112"
"Date::Manip::Offset::off113" "Date::Manip::Offset::off114"
"Date::Manip::Offset::off115" "Date::Manip::Offset::off116"
"Date::Manip::Offset::off117" "Date::Manip::Offset::off118"
"Date::Manip::Offset::off119" "Date::Manip::Offset::off120"
"Date::Manip::Offset::off121" "Date::Manip::Offset::off122"
"Date::Manip::Offset::off123" "Date::Manip::Offset::off124"
"Date::Manip::Offset::off125" "Date::Manip::Offset::off126"
"Date::Manip::Offset::off127" "Date::Manip::Offset::off128"
"Date::Manip::Offset::off129" "Date::Manip::Offset::off130"
"Date::Manip::Offset::off131" "Date::Manip::Offset::off132"
"Date::Manip::Offset::off133" "Date::Manip::Offset::off134"
"Date::Manip::Offset::off135" "Date::Manip::Offset::off136"
"Date::Manip::Offset::off137" "Date::Manip::Offset::off138"
"Date::Manip::Offset::off139" "Date::Manip::Offset::off140"
"Date::Manip::Offset::off141" "Date::Manip::Offset::off142"
"Date::Manip::Offset::off143" "Date::Manip::Offset::off144"
"Date::Manip::Offset::off145" "Date::Manip::Offset::off146"
"Date::Manip::Offset::off147" "Date::Manip::Offset::off148"
"Date::Manip::Offset::off149" "Date::Manip::Offset::off150"
"Date::Manip::Offset::off151" "Date::Manip::Offset::off152"
"Date::Manip::Offset::off153" "Date::Manip::Offset::off154"
"Date::Manip::Offset::off155" "Date::Manip::Offset::off156"
"Date::Manip::Offset::off157" "Date::Manip::Offset::off158"
"Date::Manip::Offset::off159" "Date::Manip::Offset::off160"
"Date::Manip::Offset::off161" "Date::Manip::Offset::off162"
"Date::Manip::Offset::off163" "Date::Manip::Offset::off164"
"Date::Manip::Offset::off165" "Date::Manip::Offset::off166"
"Date::Manip::Offset::off167" "Date::Manip::Offset::off168"
"Date::Manip::Offset::off169" "Date::Manip::Offset::off170"
"Date::Manip::Offset::off171" "Date::Manip::Offset::off172"
"Date::Manip::Offset::off173" "Date::Manip::Offset::off174"
"Date::Manip::Offset::off175" "Date::Manip::Offset::off176"
"Date::Manip::Offset::off177" "Date::Manip::Offset::off178"
"Date::Manip::Offset::off179" "Date::Manip::Offset::off180"
"Date::Manip::Offset::off181" "Date::Manip::Offset::off182"
"Date::Manip::Offset::off183" "Date::Manip::Offset::off184"
"Date::Manip::Offset::off185" "Date::Manip::Offset::off186"
"Date::Manip::Offset::off187" "Date::Manip::Offset::off188"
"Date::Manip::Offset::off189" "Date::Manip::Offset::off190"
"Date::Manip::Offset::off191" "Date::Manip::Offset::off192"
"Date::Manip::Offset::off193" "Date::Manip::Offset::off194"
"Date::Manip::Offset::off195" "Date::Manip::Offset::off196"
"Date::Manip::Offset::off197" "Date::Manip::Offset::off198"
"Date::Manip::Offset::off199" "Date::Manip::Offset::off200"
"Date::Manip::Offset::off201" "Date::Manip::Offset::off202"
"Date::Manip::Offset::off203" "Date::Manip::Offset::off204"
"Date::Manip::Offset::off205" "Date::Manip::Offset::off206"
"Date::Manip::Offset::off207" "Date::Manip::Offset::off208"
"Date::Manip::Offset::off209" "Date::Manip::Offset::off210"
"Date::Manip::Offset::off211" "Date::Manip::Offset::off212"
"Date::Manip::Offset::off213" "Date::Manip::Offset::off214"
"Date::Manip::Offset::off215" "Date::Manip::Offset::off216"
"Date::Manip::Offset::off217" "Date::Manip::Offset::off218"
"Date::Manip::Offset::off219" "Date::Manip::Offset::off220"
"Date::Manip::Offset::off221" "Date::Manip::Offset::off222"
"Date::Manip::Offset::off223" "Date::Manip::Offset::off224"
"Date::Manip::Offset::off225" "Date::Manip::Offset::off226"
"Date::Manip::Offset::off227" "Date::Manip::Offset::off228"
"Date::Manip::Offset::off229" "Date::Manip::Offset::off230"
"Date::Manip::Offset::off231" "Date::Manip::Offset::off232"
"Date::Manip::Offset::off233" "Date::Manip::Offset::off234"
"Date::Manip::Offset::off235" "Date::Manip::Offset::off236"
"Date::Manip::Offset::off237" "Date::Manip::Offset::off238"
"Date::Manip::Offset::off239" "Date::Manip::Offset::off240"
"Date::Manip::Offset::off241" "Date::Manip::Offset::off242"
"Date::Manip::Offset::off243" "Date::Manip::Offset::off244"
"Date::Manip::Offset::off245" "Date::Manip::Offset::off246"
"Date::Manip::Offset::off247" "Date::Manip::Offset::off248"
"Date::Manip::Offset::off249" "Date::Manip::Offset::off250"
"Date::Manip::Offset::off251" "Date::Manip::Offset::off252"
"Date::Manip::Offset::off253" "Date::Manip::Offset::off254"
"Date::Manip::Offset::off255" "Date::Manip::Offset::off256"
"Date::Manip::Offset::off257" "Date::Manip::Offset::off258"
"Date::Manip::Offset::off259" "Date::Manip::Offset::off260"
"Date::Manip::Offset::off261" "Date::Manip::Offset::off262"
"Date::Manip::Offset::off263" "Date::Manip::Offset::off264"
"Date::Manip::Offset::off265" "Date::Manip::Offset::off266"
"Date::Manip::Offset::off267" "Date::Manip::Offset::off268"
"Date::Manip::Offset::off269" "Date::Manip::Offset::off270"
"Date::Manip::Offset::off271" "Date::Manip::Offset::off272"
"Date::Manip::Offset::off273" "Date::Manip::Offset::off274"
"Date::Manip::Offset::off275" "Date::Manip::Offset::off276"
"Date::Manip::Offset::off277" "Date::Manip::Offset::off278"
"Date::Manip::Offset::off279" "Date::Manip::Offset::off280"
"Date::Manip::Offset::off281" "Date::Manip::Offset::off282"
"Date::Manip::Offset::off283" "Date::Manip::Offset::off284"
"Date::Manip::Offset::off285" "Date::Manip::Offset::off286"
"Date::Manip::Offset::off287" "Date::Manip::Offset::off288"
"Date::Manip::Offset::off289" "Date::Manip::Offset::off290"
"Date::Manip::Offset::off291" "Date::Manip::Offset::off292"
"Date::Manip::Offset::off293" "Date::Manip::Offset::off294"
"Date::Manip::Offset::off295" "Date::Manip::Offset::off296"
"Date::Manip::Offset::off297" "Date::Manip::Offset::off298"
"Date::Manip::Offset::off299" "Date::Manip::Offset::off300"
"Date::Manip::Offset::off301" "Date::Manip::Offset::off302"
"Date::Manip::Offset::off303" "Date::Manip::Offset::off304"
"Date::Manip::Offset::off305" "Date::Manip::Offset::off306"
"Date::Manip::Offset::off307" "Date::Manip::Offset::off308"
"Date::Manip::Offset::off309" "Date::Manip::Offset::off310"
"Date::Manip::Offset::off311" "Date::Manip::Offset::off312"
"Date::Manip::Offset::off313" "Date::Manip::Offset::off314"
"Date::Manip::Offset::off315" "Date::Manip::Offset::off316"
"Date::Manip::Offset::off317" "Date::Manip::Offset::off318"
"Date::Manip::Offset::off319" "Date::Manip::Offset::off320"
"Date::Manip::Offset::off321" "Date::Manip::Offset::off322"
"Date::Manip::Offset::off323" "Date::Manip::Offset::off324"
"Date::Manip::Offset::off325" "Date::Manip::Offset::off326"
"Date::Manip::Offset::off327" "Date::Manip::Offset::off328"
"Date::Manip::Offset::off329" "Date::Manip::Offset::off330"
"Date::Manip::Offset::off331" "Date::Manip::Offset::off332"
"Date::Manip::Offset::off333" "Date::Manip::Offset::off334"
"Date::Manip::Offset::off335" "Date::Manip::Offset::off336"
"Date::Manip::Offset::off337" "Date::Manip::Offset::off338"
"Date::Manip::Offset::off339" "Date::Manip::Offset::off340"
"Date::Manip::Offset::off341" "Date::Manip::Offset::off342"
"Date::Manip::Offset::off343" "Date::Manip::Offset::off344"
"Date::Manip::Offset::off345" "Date::Manip::Offset::off346"
"Date::Manip::Offset::off347" "Date::Manip::Offset::off348"
"Date::Manip::Offset::off349" "Date::Manip::Offset::off350"
"Date::Manip::Offset::off351" "Date::Manip::Offset::off352"
"Date::Manip::Offset::off353" "Date::Manip::Offset::off354"
"Date::Manip::Offset::off355" "Date::Manip::Offset::off356"
"Date::Manip::Offset::off357" "Date::Manip::Offset::off358"
"Date::Manip::Offset::off359" "Date::Manip::Offset::off360"
"Date::Manip::Offset::off361" "Date::Manip::Offset::off362"
"Date::Manip::Offset::off363" "Date::Manip::Offset::off364"
"Date::Manip::Offset::off365" "Date::Manip::Offset::off366"
"Date::Manip::Offset::off367" "Date::Manip::Offset::off368"
"Date::Manip::Offset::off369" "Date::Manip::Offset::off370"
"Date::Manip::Offset::off371" "Date::Manip::Offset::off372"
"Date::Manip::Offset::off373" "Date::Manip::Offset::off374"
"Date::Manip::Offset::off375" "Date::Manip::Offset::off376"
"Date::Manip::Offset::off377" "Date::Manip::Offset::off378"
"Date::Manip::Offset::off379" "Date::Manip::Offset::off380"
"Date::Manip::Offset::off381" "Date::Manip::Offset::off382"
"Date::Manip::Offset::off383" "Date::Manip::Offset::off384"
"Date::Manip::Offset::off385" "Date::Manip::Offset::off386"
"Date::Manip::Offset::off387" "Date::Manip::Offset::off388"
"Date::Manip::Offset::off389" "Date::Manip::Offset::off390"
"Date::Manip::Offset::off391" "Date::Manip::Offset::off392"
"Date::Manip::Offset::off393" "Date::Manip::Offset::off394"
"Date::Manip::Offset::off395" "Date::Manip::Offset::off396"
"Date::Manip::Offset::off397" "Date::Manip::Offset::off398"
"Date::Manip::Offset::off399" "Date::Manip::Offset::off400"
"Date::Manip::Offset::off401" "Date::Manip::Offset::off402"
"Date::Manip::Offset::off403" "Date::Manip::Offset::off404"
"Date::Manip::Offset::off405" "Date::Manip::Offset::off406"
"Date::Manip::Offset::off407" "Date::Manip::Offset::off408"
"Date::Manip::Offset::off409" "Date::Manip::Offset::off410"
"Date::Manip::Offset::off411" "Date::Manip::Offset::off412"
"Date::Manip::Offset::off413" "Date::Manip::Offset::off414"
"Date::Manip::Offset::off415" "Date::Manip::Offset::off416"
"Date::Manip::Offset::off417" "Date::Manip::Offset::off418"
"Date::Manip::Offset::off419" "Date::Manip::Offset::off420"
"Date::Manip::Offset::off421" "Date::Manip::Offset::off422"
"Date::Manip::Offset::off423" "Date::Manip::Offset::off424"
"Date::Manip::Offset::off425" "Date::Manip::Offset::off426"
"Date::Manip::Offset::off427" "Date::Manip::Offset::off428"
"Date::Manip::Offset::off429" "Date::Manip::Offset::off430"
"Date::Manip::Offset::off431" "Date::Manip::Offset::off432"
"Date::Manip::Offset::off433" "Date::Manip::Offset::off434"
"Date::Manip::Offset::off435" "Date::Manip::Offset::off436"
"Date::Manip::Offset::off437" "Date::Manip::Offset::off438"
"Date::Manip::Offset::off439" "Date::Manip::Offset::off440"
"Date::Manip::Offset::off441" "Date::Manip::Offset::off442"
"Date::Manip::Offset::off443" "Date::Manip::Offset::off444"
"Date::Manip::Offset::off445" "Date::Manip::Offset::off446"
"Date::Manip::Offset::off447" "Date::Manip::Offset::off448"
"Date::Manip::Offset::off449" "Date::Manip::Offset::off450"
"Date::Manip::Offset::off451" "Date::Manip::Offset::off452"
"Date::Manip::Offset::off453" "Date::Manip::Offset::off454"
"Date::Manip::Offset::off455" "Date::Manip::Offset::off456"
"Date::Manip::Offset::off457" "Date::Manip::Offset::off458"
"Date::Manip::Offset::off459" "Date::Manip::Offset::off460"
"Date::Manip::Offset::off461" "Date::Manip::Offset::off462"
"Date::Manip::Offset::off463" "Date::Manip::Offset::off464"
"Date::Manip::Offset::off465" "Date::Manip::Offset::off466"
"Date::Manip::Offset::off467" "Date::Manip::Offset::off468"
"Date::Manip::Offset::off469" "Date::Manip::Offset::off470"
"Date::Manip::Offset::off471" "Date::Manip::Offset::off472"
"Date::Manip::Offset::off473" "Date::Manip::Offset::off474"
"Date::Manip::Offset::off475" "Date::Manip::Offset::off476"
"Date::Manip::Offset::off477" "Date::Manip::Offset::off478"
"Date::Manip::Offset::off479" "Date::Manip::Offset::off480"
"Date::Manip::Offset::off481" "Date::Manip::Offset::off482"
"Date::Manip::Offset::off483" "Date::Manip::Offset::off484"
"Date::Manip::Offset::off485" "Date::Manip::Offset::off486"
"Date::Manip::Offset::off487" "Date::Manip::Offset::off488"
"Date::Manip::Recur" "Date::Manip::TZ" "Date::Manip::TZ::a00"
"Date::Manip::TZ::afabid00" "Date::Manip::TZ::afaccr00"
"Date::Manip::TZ::afaddi00" "Date::Manip::TZ::afalgi00"
"Date::Manip::TZ::afasma00" "Date::Manip::TZ::afbama00"
"Date::Manip::TZ::afbang00" "Date::Manip::TZ::afbanj00"
"Date::Manip::TZ::afbiss00" "Date::Manip::TZ::afblan00"
"Date::Manip::TZ::afbraz00" "Date::Manip::TZ::afbuju00"
"Date::Manip::TZ::afcair00" "Date::Manip::TZ::afcasa00"
"Date::Manip::TZ::afceut00" "Date::Manip::TZ::afcona00"
"Date::Manip::TZ::afdaka00" "Date::Manip::TZ::afdar_00"
"Date::Manip::TZ::afdjib00" "Date::Manip::TZ::afdoua00"
"Date::Manip::TZ::afel_a00" "Date::Manip::TZ::affree00"
"Date::Manip::TZ::afgabo00" "Date::Manip::TZ::afhara00"
"Date::Manip::TZ::afjoha00" "Date::Manip::TZ::afjuba00"
"Date::Manip::TZ::afkamp00" "Date::Manip::TZ::afkhar00"
"Date::Manip::TZ::afkiga00" "Date::Manip::TZ::afkins00"
"Date::Manip::TZ::aflago00" "Date::Manip::TZ::aflibr00"
"Date::Manip::TZ::aflome00" "Date::Manip::TZ::afluan00"
"Date::Manip::TZ::aflubu00" "Date::Manip::TZ::aflusa00"
"Date::Manip::TZ::afmala00" "Date::Manip::TZ::afmapu00"
"Date::Manip::TZ::afmase00" "Date::Manip::TZ::afmbab00"
"Date::Manip::TZ::afmoga00" "Date::Manip::TZ::afmonr00"
"Date::Manip::TZ::afnair00" "Date::Manip::TZ::afndja00"
"Date::Manip::TZ::afniam00" "Date::Manip::TZ::afnoua00"
"Date::Manip::TZ::afouag00" "Date::Manip::TZ::afport00"
"Date::Manip::TZ::afsao_00" "Date::Manip::TZ::aftrip00"
"Date::Manip::TZ::aftuni00" "Date::Manip::TZ::afwind00"
"Date::Manip::TZ::amadak00" "Date::Manip::TZ::amanch00"
"Date::Manip::TZ::amangu00" "Date::Manip::TZ::amanti00"
"Date::Manip::TZ::amarag00" "Date::Manip::TZ::amarub00"
"Date::Manip::TZ::amasun00" "Date::Manip::TZ::amatik00"
"Date::Manip::TZ::ambahi00" "Date::Manip::TZ::ambahi01"
"Date::Manip::TZ::ambarb00" "Date::Manip::TZ::ambele00"
"Date::Manip::TZ::ambeli00" "Date::Manip::TZ::ambeul00"
"Date::Manip::TZ::amblan00" "Date::Manip::TZ::amboa_00"
"Date::Manip::TZ::ambogo00" "Date::Manip::TZ::ambois00"
"Date::Manip::TZ::ambuen00" "Date::Manip::TZ::amcamb00"
"Date::Manip::TZ::amcamp00" "Date::Manip::TZ::amcanc00"
"Date::Manip::TZ::amcara00" "Date::Manip::TZ::amcata00"
"Date::Manip::TZ::amcaye00" "Date::Manip::TZ::amcaym00"
"Date::Manip::TZ::amcent00" "Date::Manip::TZ::amchic00"
"Date::Manip::TZ::amchih00" "Date::Manip::TZ::amcord00"
"Date::Manip::TZ::amcost00" "Date::Manip::TZ::amcres00"
"Date::Manip::TZ::amcuia00" "Date::Manip::TZ::amcura00"
"Date::Manip::TZ::amdanm00" "Date::Manip::TZ::amdaws00"
"Date::Manip::TZ::amdaws01" "Date::Manip::TZ::amdenv00"
"Date::Manip::TZ::amdetr00" "Date::Manip::TZ::amdomi00"
"Date::Manip::TZ::amedmo00" "Date::Manip::TZ::ameiru00"
"Date::Manip::TZ::amel_s00" "Date::Manip::TZ::amfort00"
"Date::Manip::TZ::amglac00" "Date::Manip::TZ::amgodt00"
"Date::Manip::TZ::amgoos00" "Date::Manip::TZ::amgran00"
"Date::Manip::TZ::amgren00" "Date::Manip::TZ::amguad00"
"Date::Manip::TZ::amguat00" "Date::Manip::TZ::amguay00"
"Date::Manip::TZ::amguya00" "Date::Manip::TZ::amhali00"
"Date::Manip::TZ::amhava00" "Date::Manip::TZ::amherm00"
"Date::Manip::TZ::amindi00" "Date::Manip::TZ::aminuv00"
"Date::Manip::TZ::amiqal00" "Date::Manip::TZ::amjama00"
"Date::Manip::TZ::amjuju00" "Date::Manip::TZ::amjune00"
"Date::Manip::TZ::amknox00" "Date::Manip::TZ::amla_p00"
"Date::Manip::TZ::amla_r00" "Date::Manip::TZ::amlima00"
"Date::Manip::TZ::amlos_00" "Date::Manip::TZ::amloui00"
"Date::Manip::TZ::ammace00" "Date::Manip::TZ::ammana00"
"Date::Manip::TZ::ammana01" "Date::Manip::TZ::ammare00"
"Date::Manip::TZ::ammart00" "Date::Manip::TZ::ammata00"
"Date::Manip::TZ::ammaza00" "Date::Manip::TZ::ammend00"
"Date::Manip::TZ::ammeno00" "Date::Manip::TZ::ammeri00"
"Date::Manip::TZ::ammetl00" "Date::Manip::TZ::ammexi00"
"Date::Manip::TZ::ammiqu00" "Date::Manip::TZ::ammonc00"
"Date::Manip::TZ::ammont00" "Date::Manip::TZ::ammont01"
"Date::Manip::TZ::ammont02" "Date::Manip::TZ::ammont03"
"Date::Manip::TZ::ammont04" "Date::Manip::TZ::amnass00"
"Date::Manip::TZ::amnew_00" "Date::Manip::TZ::amnew_01"
"Date::Manip::TZ::amnipi00" "Date::Manip::TZ::amnome00"
"Date::Manip::TZ::amnoro00" "Date::Manip::TZ::amojin00"
"Date::Manip::TZ::ampana00" "Date::Manip::TZ::ampang00"
"Date::Manip::TZ::ampara00" "Date::Manip::TZ::ampete00"
"Date::Manip::TZ::amphoe00" "Date::Manip::TZ::amport00"
"Date::Manip::TZ::amport01" "Date::Manip::TZ::amport02"
"Date::Manip::TZ::ampuer00" "Date::Manip::TZ::amrain00"
"Date::Manip::TZ::amrank00" "Date::Manip::TZ::amreci00"
"Date::Manip::TZ::amregi00" "Date::Manip::TZ::amreso00"
"Date::Manip::TZ::amrio_00" "Date::Manip::TZ::amrio_01"
"Date::Manip::TZ::amsalt00" "Date::Manip::TZ::amsan_00"
"Date::Manip::TZ::amsan_01" "Date::Manip::TZ::amsant00"
"Date::Manip::TZ::amsant01" "Date::Manip::TZ::amsant02"
"Date::Manip::TZ::amsant03" "Date::Manip::TZ::amsao_00"
"Date::Manip::TZ::amscor00" "Date::Manip::TZ::amsitk00"
"Date::Manip::TZ::amst_j00" "Date::Manip::TZ::amst_k00"
"Date::Manip::TZ::amst_l00" "Date::Manip::TZ::amst_t00"
"Date::Manip::TZ::amst_v00" "Date::Manip::TZ::amswif00"
"Date::Manip::TZ::amtegu00" "Date::Manip::TZ::amtell00"
"Date::Manip::TZ::amthul00" "Date::Manip::TZ::amthun00"
"Date::Manip::TZ::amtiju00" "Date::Manip::TZ::amtoro00"
"Date::Manip::TZ::amtort00" "Date::Manip::TZ::amtucu00"
"Date::Manip::TZ::amushu00" "Date::Manip::TZ::amvanc00"
"Date::Manip::TZ::amveva00" "Date::Manip::TZ::amvinc00"
"Date::Manip::TZ::amwhit00" "Date::Manip::TZ::amwina00"
"Date::Manip::TZ::amwinn00" "Date::Manip::TZ::amyaku00"
"Date::Manip::TZ::amyell00" "Date::Manip::TZ::ancase00"
"Date::Manip::TZ::andavi00" "Date::Manip::TZ::andumo00"
"Date::Manip::TZ::anmacq00" "Date::Manip::TZ::anmaws00"
"Date::Manip::TZ::anmcmu00" "Date::Manip::TZ::anpalm00"
"Date::Manip::TZ::anroth00" "Date::Manip::TZ::ansyow00"
"Date::Manip::TZ::anvost00" "Date::Manip::TZ::asaden00"
"Date::Manip::TZ::asalma00" "Date::Manip::TZ::asamma00"
"Date::Manip::TZ::asanad00" "Date::Manip::TZ::asaqta00"
"Date::Manip::TZ::asaqto00" "Date::Manip::TZ::asashg00"
"Date::Manip::TZ::asbagh00" "Date::Manip::TZ::asbahr00"
"Date::Manip::TZ::asbaku00" "Date::Manip::TZ::asbang00"
"Date::Manip::TZ::asbeir00" "Date::Manip::TZ::asbish00"
"Date::Manip::TZ::asbrun00" "Date::Manip::TZ::aschoi00"
"Date::Manip::TZ::aschon00" "Date::Manip::TZ::ascolo00"
"Date::Manip::TZ::asdama00" "Date::Manip::TZ::asdhak00"
"Date::Manip::TZ::asdili00" "Date::Manip::TZ::asduba00"
"Date::Manip::TZ::asdush00" "Date::Manip::TZ::asgaza00"
"Date::Manip::TZ::asharb00" "Date::Manip::TZ::ashebr00"
"Date::Manip::TZ::asho_c00" "Date::Manip::TZ::ashong00"
"Date::Manip::TZ::ashovd00" "Date::Manip::TZ::asirku00"
"Date::Manip::TZ::asjaka00" "Date::Manip::TZ::asjaya00"
"Date::Manip::TZ::asjeru00" "Date::Manip::TZ::askabu00"
"Date::Manip::TZ::askamc00" "Date::Manip::TZ::askara00"
"Date::Manip::TZ::askash00" "Date::Manip::TZ::askath00"
"Date::Manip::TZ::askolk00" "Date::Manip::TZ::askras00"
"Date::Manip::TZ::askual00" "Date::Manip::TZ::askuch00"
"Date::Manip::TZ::askuwa00" "Date::Manip::TZ::asmaca00"
"Date::Manip::TZ::asmaga00" "Date::Manip::TZ::asmaka00"
"Date::Manip::TZ::asmani00" "Date::Manip::TZ::asmusc00"
"Date::Manip::TZ::asnico00" "Date::Manip::TZ::asnovo00"
"Date::Manip::TZ::asnovo01" "Date::Manip::TZ::asomsk00"
"Date::Manip::TZ::asoral00" "Date::Manip::TZ::asphno00"
"Date::Manip::TZ::aspont00" "Date::Manip::TZ::aspyon00"
"Date::Manip::TZ::asqata00" "Date::Manip::TZ::asqyzy00"
"Date::Manip::TZ::asrang00" "Date::Manip::TZ::asriya00"
"Date::Manip::TZ::assakh00" "Date::Manip::TZ::assama00"
"Date::Manip::TZ::asseou00" "Date::Manip::TZ::asshan00"
"Date::Manip::TZ::assing00" "Date::Manip::TZ::astaip00"
"Date::Manip::TZ::astash00" "Date::Manip::TZ::astbil00"
"Date::Manip::TZ::astehr00" "Date::Manip::TZ::asthim00"
"Date::Manip::TZ::astoky00" "Date::Manip::TZ::asulaa00"
"Date::Manip::TZ::asurum00" "Date::Manip::TZ::asvien00"
"Date::Manip::TZ::asvlad00" "Date::Manip::TZ::asyaku00"
"Date::Manip::TZ::asyeka00" "Date::Manip::TZ::asyere00"
"Date::Manip::TZ::atazor00" "Date::Manip::TZ::atberm00"
"Date::Manip::TZ::atcana00" "Date::Manip::TZ::atcape00"
"Date::Manip::TZ::atfaro00" "Date::Manip::TZ::atmade00"
"Date::Manip::TZ::atreyk00" "Date::Manip::TZ::atsout00"
"Date::Manip::TZ::atst_h00" "Date::Manip::TZ::atstan00"
"Date::Manip::TZ::auadel00" "Date::Manip::TZ::aubris00"
"Date::Manip::TZ::aubrok00" "Date::Manip::TZ::aucurr00"
"Date::Manip::TZ::audarw00" "Date::Manip::TZ::aueucl00"
"Date::Manip::TZ::auhoba00" "Date::Manip::TZ::aulind00"
"Date::Manip::TZ::aulord00" "Date::Manip::TZ::aumelb00"
"Date::Manip::TZ::aupert00" "Date::Manip::TZ::ausydn00"
"Date::Manip::TZ::b00" "Date::Manip::TZ::c00" "Date::Manip::TZ::cet00"
"Date::Manip::TZ::d00" "Date::Manip::TZ::e00" "Date::Manip::TZ::eet00"
"Date::Manip::TZ::etgmt00" "Date::Manip::TZ::etgmtm00"
"Date::Manip::TZ::etgmtm01" "Date::Manip::TZ::etgmtm02"
"Date::Manip::TZ::etgmtm03" "Date::Manip::TZ::etgmtm04"
"Date::Manip::TZ::etgmtm05" "Date::Manip::TZ::etgmtm06"
"Date::Manip::TZ::etgmtm07" "Date::Manip::TZ::etgmtm08"
"Date::Manip::TZ::etgmtm09" "Date::Manip::TZ::etgmtm10"
"Date::Manip::TZ::etgmtm11" "Date::Manip::TZ::etgmtm12"
"Date::Manip::TZ::etgmtm13" "Date::Manip::TZ::etgmtp00"
"Date::Manip::TZ::etgmtp01" "Date::Manip::TZ::etgmtp02"
"Date::Manip::TZ::etgmtp03" "Date::Manip::TZ::etgmtp04"
"Date::Manip::TZ::etgmtp05" "Date::Manip::TZ::etgmtp06"
"Date::Manip::TZ::etgmtp07" "Date::Manip::TZ::etgmtp08"
"Date::Manip::TZ::etgmtp09" "Date::Manip::TZ::etgmtp10"
"Date::Manip::TZ::etgmtp11" "Date::Manip::TZ::euamst00"
"Date::Manip::TZ::euando00" "Date::Manip::TZ::euathe00"
"Date::Manip::TZ::eubelg00" "Date::Manip::TZ::euberl00"
"Date::Manip::TZ::eubrus00" "Date::Manip::TZ::eubuch00"
"Date::Manip::TZ::eubuda00" "Date::Manip::TZ::euchis00"
"Date::Manip::TZ::eucope00" "Date::Manip::TZ::eudubl00"
"Date::Manip::TZ::eugibr00" "Date::Manip::TZ::euhels00"
"Date::Manip::TZ::euista00" "Date::Manip::TZ::eukali00"
"Date::Manip::TZ::eukiev00" "Date::Manip::TZ::eulisb00"
"Date::Manip::TZ::eulond00" "Date::Manip::TZ::euluxe00"
"Date::Manip::TZ::eumadr00" "Date::Manip::TZ::eumalt00"
"Date::Manip::TZ::eumins00" "Date::Manip::TZ::eumona00"
"Date::Manip::TZ::eumosc00" "Date::Manip::TZ::euoslo00"
"Date::Manip::TZ::eupari00" "Date::Manip::TZ::euprag00"
"Date::Manip::TZ::euriga00" "Date::Manip::TZ::eurome00"
"Date::Manip::TZ::eusama00" "Date::Manip::TZ::eusimf00"
"Date::Manip::TZ::eusofi00" "Date::Manip::TZ::eustoc00"
"Date::Manip::TZ::eutall00" "Date::Manip::TZ::eutira00"
"Date::Manip::TZ::euuzhg00" "Date::Manip::TZ::euvadu00"
"Date::Manip::TZ::euvien00" "Date::Manip::TZ::euviln00"
"Date::Manip::TZ::euvolg00" "Date::Manip::TZ::euwars00"
"Date::Manip::TZ::euzapo00" "Date::Manip::TZ::euzuri00"
"Date::Manip::TZ::f00" "Date::Manip::TZ::g00" "Date::Manip::TZ::h00"
"Date::Manip::TZ::i00" "Date::Manip::TZ::inanta00"
"Date::Manip::TZ::inchag00" "Date::Manip::TZ::inchri00"
"Date::Manip::TZ::incoco00" "Date::Manip::TZ::incomo00"
"Date::Manip::TZ::inkerg00" "Date::Manip::TZ::inmahe00"
"Date::Manip::TZ::inmald00" "Date::Manip::TZ::inmaur00"
"Date::Manip::TZ::inmayo00" "Date::Manip::TZ::inreun00"
"Date::Manip::TZ::k00" "Date::Manip::TZ::l00" "Date::Manip::TZ::m00"
"Date::Manip::TZ::met00" "Date::Manip::TZ::n00" "Date::Manip::TZ::o00"
"Date::Manip::TZ::p00" "Date::Manip::TZ::paapia00"
"Date::Manip::TZ::paauck00" "Date::Manip::TZ::pachat00"
"Date::Manip::TZ::pachuu00" "Date::Manip::TZ::paeast00"
"Date::Manip::TZ::paefat00" "Date::Manip::TZ::paende00"
"Date::Manip::TZ::pafaka00" "Date::Manip::TZ::pafiji00"
"Date::Manip::TZ::pafuna00" "Date::Manip::TZ::pagala00"
"Date::Manip::TZ::pagamb00" "Date::Manip::TZ::paguad00"
"Date::Manip::TZ::paguam00" "Date::Manip::TZ::pahono00"
"Date::Manip::TZ::pakiri00" "Date::Manip::TZ::pakosr00"
"Date::Manip::TZ::pakwaj00" "Date::Manip::TZ::pamaju00"
"Date::Manip::TZ::pamarq00" "Date::Manip::TZ::pamidw00"
"Date::Manip::TZ::panaur00" "Date::Manip::TZ::paniue00"
"Date::Manip::TZ::panorf00" "Date::Manip::TZ::panoum00"
"Date::Manip::TZ::papago00" "Date::Manip::TZ::papala00"
"Date::Manip::TZ::papitc00" "Date::Manip::TZ::papohn00"
"Date::Manip::TZ::paport00" "Date::Manip::TZ::pararo00"
"Date::Manip::TZ::pasaip00" "Date::Manip::TZ::patahi00"
"Date::Manip::TZ::patara00" "Date::Manip::TZ::patong00"
"Date::Manip::TZ::pawake00" "Date::Manip::TZ::pawall00"
"Date::Manip::TZ::q00" "Date::Manip::TZ::r00" "Date::Manip::TZ::s00"
"Date::Manip::TZ::t00" "Date::Manip::TZ::u00" "Date::Manip::TZ::ut00"
"Date::Manip::TZ::utc00" "Date::Manip::TZ::v00" "Date::Manip::TZ::w00"
"Date::Manip::TZ::wet00" "Date::Manip::TZ::x00" "Date::Manip::TZ::y00"
"Date::Manip::TZ::z00" "Date::Manip::TZ_Base" "Date::Manip::TZdata"
"Date::Manip::Zones" "Devel::InnerPackage" "Devel::PPPort" "Devel::Peek"
"Devel::SelfStubber" "Digest" "Digest::MD5" "Digest::SHA" "Digest::base"
"Digest::file" "DirHandle" "Dumpvalue" "DynaLoader" "Encode"
"Encode::Alias" "Encode::Byte" "Encode::CJKConstants" "Encode::CN"
"Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC" "Encode::Encoder"
"Encode::Encoding" "Encode::GSM0338" "Encode::Guess" "Encode::JP"
"Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::Locale" "Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::Symbol" "Encode::TW" "Encode::Unicode"
"Encode::Unicode::UTF7" "English" "Env" "Errno" "Error" "Error::Simple"
"Exporter" "Exporter::Heavy" "ExtUtils::CBuilder"
"ExtUtils::CBuilder::Base" "ExtUtils::CBuilder::Platform::Unix"
"ExtUtils::CBuilder::Platform::VMS" "ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config" "ExtUtils::Manifest"
"ExtUtils::Miniperl" "ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists"
"ExtUtils::Packlist" "ExtUtils::ParseXS" "ExtUtils::ParseXS::Constants"
"ExtUtils::ParseXS::CountLines" "ExtUtils::ParseXS::Utilities"
"ExtUtils::Typemaps" "ExtUtils::Typemaps::Cmd"
"ExtUtils::Typemaps::InputMap" "ExtUtils::Typemaps::OutputMap"
"ExtUtils::Typemaps::Type" "ExtUtils::testlib" "Fatal" "Fcntl"
"File::Basename" "File::CheckTree" "File::Compare" "File::Copy"
"File::DosGlob" "File::Fetch" "File::Find" "File::Glob" "File::GlobMapper"
"File::Listing" "File::Path" "File::ReadBackwards" "File::Spec"
"File::Spec::Cygwin" "File::Spec::Epoc" "File::Spec::Functions"
"File::Spec::Mac" "File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS"
"File::Spec::Win32" "File::Tail" "File::Temp" "File::stat" "FileCache"
"FileHandle" "Filter::Simple" "Filter::Util::Call" "FindBin" "Foomatic::DB"
"Foomatic::Defaults" "Foomatic::PPD" "Foomatic::UIElem" "GDBM_File"
"Getopt::Long" "Getopt::Std" "Git" "Git::I18N" "Git::SVN::Editor"
"Git::SVN::Fetcher" "Git::SVN::Memoize::YAML" "Git::SVN::Prompt"
"Git::SVN::Ra" "HTML::Entities" "HTML::Filter" "HTML::HeadParser"
"HTML::LinkExtor" "HTML::Parser" "HTML::PullParser" "HTML::Tagset"
"HTML::TokeParser" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "HTTP::Tiny"
"Hash::Util" "Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "I18N::Langinfo" "IO"
"IO::Compress::Adapter::Bzip2" "IO::Compress::Adapter::Deflate"
"IO::Compress::Adapter::Identity" "IO::Compress::Base"
"IO::Compress::Base::Common" "IO::Compress::Bzip2" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants"
"IO::Compress::RawDeflate" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle" "IO::Pipe"
"IO::Poll" "IO::Seekable" "IO::Select" "IO::Socket" "IO::Socket::INET"
"IO::Socket::UNIX" "IO::Uncompress::Adapter::Bunzip2"
"IO::Uncompress::Adapter::Identity" "IO::Uncompress::Adapter::Inflate"
"IO::Uncompress::AnyInflate" "IO::Uncompress::AnyUncompress"
"IO::Uncompress::Base" "IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Zlib" "IPC::Cmd" "IPC::Msg" "IPC::Open2"
"IPC::Open3" "IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "Image::Magick"
"JSON::PP" "JSON::PP::Boolean" "JSON::Syck" "LWP" "LWP::Authen::Basic"
"LWP::Authen::Digest" "LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug"
"LWP::DebugFile" "LWP::MediaTypes" "LWP::MemberMixin" "LWP::Protocol"
"LWP::Protocol::GHTTP" "LWP::Protocol::cpan" "LWP::Protocol::data"
"LWP::Protocol::file" "LWP::Protocol::ftp" "LWP::Protocol::gopher"
"LWP::Protocol::http" "LWP::Protocol::loopback" "LWP::Protocol::mailto"
"LWP::Protocol::nntp" "LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple"
"LWP::UserAgent" "List::Util" "List::Util::XS" "Locale::Codes"
"Locale::Codes::Constants" "Locale::Codes::Country"
"Locale::Codes::Country_Codes" "Locale::Codes::Country_Retired"
"Locale::Codes::Currency" "Locale::Codes::Currency_Codes"
"Locale::Codes::Currency_Retired" "Locale::Codes::LangExt"
"Locale::Codes::LangExt_Codes" "Locale::Codes::LangExt_Retired"
"Locale::Codes::LangFam" "Locale::Codes::LangFam_Codes"
"Locale::Codes::LangFam_Retired" "Locale::Codes::LangVar"
"Locale::Codes::LangVar_Codes" "Locale::Codes::LangVar_Retired"
"Locale::Codes::Language" "Locale::Codes::Language_Codes"
"Locale::Codes::Language_Retired" "Locale::Codes::Script"
"Locale::Codes::Script_Codes" "Locale::Codes::Script_Retired"
"Locale::Country" "Locale::Currency" "Locale::Language" "Locale::Maketext"
"Locale::Maketext::Guts" "Locale::Maketext::GutsLoader"
"Locale::Maketext::Simple" "Locale::Script" "Log::Message"
"Log::Message::Config" "Log::Message::Handlers" "Log::Message::Item"
"Log::Message::Simple" "MIME::Base64" "MIME::QuotedPrint" "Math::BigFloat"
"Math::BigFloat::Trace" "Math::BigInt" "Math::BigInt::Calc"
"Math::BigInt::CalcEmu" "Math::BigInt::FastCalc" "Math::BigInt::Trace"
"Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Build" "Module::Build::Base"
"Module::Build::Compat" "Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Load" "Module::Load::Conditional" "Module::Loaded"
"Module::Metadata" "Module::Pluggable" "Module::Pluggable::Object"
"NDBM_File" "NEXT" "Net::Cmd" "Net::Config" "Net::Domain" "Net::FTP"
"Net::FTP::A" "Net::FTP::E" "Net::FTP::I" "Net::FTP::L"
"Net::FTP::dataconn" "Net::HTTP" "Net::HTTP::Methods" "Net::HTTP::NB"
"Net::HTTPS" "Net::Libproxy" "Net::NNTP" "Net::Netrc" "Net::POP3"
"Net::Ping" "Net::SMTP" "Net::Time" "Net::hostent" "Net::netent"
"Net::protoent" "Net::servent" "NetSNMP::ASN" "NetSNMP::OID"
"NetSNMP::TrapReceiver" "NetSNMP::agent" "NetSNMP::agent::Support"
"NetSNMP::agent::default_store" "NetSNMP::agent::netsnmp_request_infoPtr"
"NetSNMP::default_store" "O" "ODBM_File" "Object::Accessor" "Opcode"
"POSIX" "Package::Constants" "Params::Check" "Parse::CPAN::Meta"
"Perl::OSType" "PerlIO" "PerlIO::encoding" "PerlIO::mmap" "PerlIO::scalar"
"PerlIO::via" "PerlIO::via::QuotedPrint" "Pod::Checker" "Pod::Escapes"
"Pod::Find" "Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX"
"Pod::Man" "Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToANSI"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToTerm"
"Pod::Perldoc::ToText" "Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml"
"Pod::PlainText" "Pod::Select" "Pod::Simple" "Pod::Simple::BlackBox"
"Pod::Simple::Checker" "Pod::Simple::Debug" "Pod::Simple::DumpAsText"
"Pod::Simple::DumpAsXML" "Pod::Simple::HTML" "Pod::Simple::HTMLBatch"
"Pod::Simple::HTMLLegacy" "Pod::Simple::LinkSection" "Pod::Simple::Methody"
"Pod::Simple::Progress" "Pod::Simple::PullParser"
"Pod::Simple::PullParserEndToken" "Pod::Simple::PullParserStartToken"
"Pod::Simple::PullParserTextToken" "Pod::Simple::PullParserToken"
"Pod::Simple::RTF" "Pod::Simple::Search" "Pod::Simple::SimpleTree"
"Pod::Simple::Text" "Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "SDBM_File"
"SNMP" "SVN::Base" "SVN::Client" "SVN::Core" "SVN::Delta" "SVN::Fs"
"SVN::Ra" "SVN::Repos" "SVN::Wc" "Safe" "Scalar::Util" "Search::Dict"
"SelectSaver" "SelfLoader" "Socket" "Storable" "Symbol" "Sys::Hostname"
"Sys::Syslog" "TAP::Base" "TAP::Formatter::Base" "TAP::Formatter::Color"
"TAP::Formatter::Console" "TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Object" "TAP::Parser" "TAP::Parser::Aggregator"
"TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::SourceHandler"
"TAP::Parser::SourceHandler::Executable" "TAP::Parser::SourceHandler::File"
"TAP::Parser::SourceHandler::Handle" "TAP::Parser::SourceHandler::Perl"
"TAP::Parser::SourceHandler::RawTAP" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer" "Template"
"Template::Base" "Template::Config" "Template::Constants"
"Template::Context" "Template::Directive" "Template::Document"
"Template::Exception" "Template::FAQ" "Template::Filters"
"Template::Grammar" "Template::Iterator" "Template::Manual"
"Template::Manual::Config" "Template::Manual::Credits"
"Template::Manual::Directives" "Template::Manual::Filters"
"Template::Manual::Internals" "Template::Manual::Intro"
"Template::Manual::Plugins" "Template::Manual::Syntax"
"Template::Manual::VMethods" "Template::Manual::Variables"
"Template::Manual::Views" "Template::Modules"
"Template::Namespace::Constants" "Template::Parser" "Template::Plugin"
"Template::Plugin::Assert" "Template::Plugin::CGI"
"Template::Plugin::Datafile" "Template::Plugin::Date"
"Template::Plugin::Directory" "Template::Plugin::Dumper"
"Template::Plugin::File" "Template::Plugin::Filter"
"Template::Plugin::Format" "Template::Plugin::HTML"
"Template::Plugin::Image" "Template::Plugin::Iterator"
"Template::Plugin::Math" "Template::Plugin::Pod"
"Template::Plugin::Procedural" "Template::Plugin::Scalar"
"Template::Plugin::String" "Template::Plugin::Table"
"Template::Plugin::URL" "Template::Plugin::View" "Template::Plugin::Wrap"
"Template::Plugins" "Template::Provider" "Template::Service"
"Template::Stash" "Template::Stash::Context" "Template::Stash::XS"
"Template::Test" "Template::Toolkit" "Template::Tools"
"Template::Tools::tpage" "Template::Tools::ttree" "Template::Tutorial"
"Template::Tutorial::Datafile" "Template::Tutorial::Web"
"Template::VMethods" "Template::View" "Term::ANSIColor" "Term::Cap"
"Term::Complete" "Term::ReadLine" "Term::UI" "Term::UI::History" "Test"
"Test::Builder" "Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Harness" "Test::More" "Test::Simple"
"Text::Abbrev" "Text::Balanced" "Text::ParseWords" "Text::Soundex"
"Text::Tabs" "Text::Wrap" "Thread" "Thread::Queue" "Thread::Semaphore"
"Tie::Array" "Tie::File" "Tie::Handle" "Tie::Hash"
"Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash" "Tie::Scalar"
"Tie::StdHandle" "Tie::SubstrHash" "Time::HiRes" "Time::Local"
"Time::Piece" "Time::Seconds" "Time::gmtime" "Time::localtime" "Time::tm"
"UNIVERSAL" "URI" "URI::Escape" "URI::Heuristic" "URI::IRI"
"URI::QueryParam" "URI::Split" "URI::URL" "URI::WithBase" "URI::_foreign"
"URI::_generic" "URI::_idna" "URI::_ldap" "URI::_login" "URI::_punycode"
"URI::_query" "URI::_segment" "URI::_server" "URI::_userpass" "URI::data"
"URI::file" "URI::file::Base" "URI::file::FAT" "URI::file::Mac"
"URI::file::OS2" "URI::file::QNX" "URI::file::Unix" "URI::file::Win32"
"URI::ftp" "URI::gopher" "URI::http" "URI::https" "URI::ldap" "URI::ldapi"
"URI::ldaps" "URI::mailto" "URI::mms" "URI::news" "URI::nntp" "URI::pop"
"URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu" "URI::sip" "URI::sips"
"URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270" "URI::urn"
"URI::urn::isbn" "URI::urn::oid" "Unicode::Collate"
"Unicode::Collate::CJK::Big5" "Unicode::Collate::CJK::GB2312"
"Unicode::Collate::CJK::JISX0208" "Unicode::Collate::CJK::Korean"
"Unicode::Collate::CJK::Pinyin" "Unicode::Collate::CJK::Stroke"
"Unicode::Collate::Locale" "Unicode::Normalize" "Unicode::UCD"
"User::grent" "User::pwent" "Version::Requirements" "WWW::RobotRules"
"WWW::RobotRules::AnyDBM_File" "XML::Parser" "XML::Parser::Expat"
"XML::Parser::Style::Debug" "XML::Parser::Style::Objects"
"XML::Parser::Style::Stream" "XML::Parser::Style::Subs"
"XML::Parser::Style::Tree" "XML::Simple" "XSLoader" "YAML::Dumper::Syck"
"YAML::Loader::Syck" "YAML::Syck" "_charnames" "a2p" "arybase" "attributes"
"autodie" "autodie::exception" "autodie::exception::system"
"autodie::hints" "autouse" "base" "bigint" "bignum" "bigrat" "blib" "bytes"
"charnames" "constant" "deprecate" "diagnostics" "encoding"
"encoding::warnings" "feature" "fields" "filetest" "gv" "if" "inc::latest"
"inc::latest::private" "integer" "less" "lib" "locale" "mro" "open.pod"
"ops" "overload" "overload::numbers" "overloading" "parent" "perl"
"perl5004delta" "perl5005delta" "perl5100delta" "perl5101delta"
"perl5120delta" "perl5121delta" "perl5122delta" "perl5123delta"
"perl5124delta" "perl5140delta" "perl5141delta" "perl5142delta"
"perl5160delta" "perl5161delta" "perl561delta" "perl56delta" "perl581delta"
"perl582delta" "perl583delta" "perl584delta" "perl585delta" "perl586delta"
"perl587delta" "perl588delta" "perl589delta" "perl58delta" "perlaix"
"perlamiga" "perlapi" "perlapio" "perlartistic" "perlbeos" "perlbook"
"perlboot" "perlbot" "perlbs2000" "perlcall" "perlce" "perlcheat"
"perlclib" "perlcn" "perlcommunity" "perlcygwin" "perldata" "perldbmfilter"
"perldebguts" "perldebtut" "perldebug" "perldelta" "perldgux" "perldiag"
"perldoc" "perldos" "perldsc" "perldtrace" "perlebcdic" "perlembed"
"perlepoc" "perlexperiment" "perlfaq" "perlfaq1" "perlfaq2" "perlfaq3"
"perlfaq4" "perlfaq5" "perlfaq6" "perlfaq7" "perlfaq8" "perlfaq9"
"perlfilter" "perlfork" "perlform" "perlfreebsd" "perlfunc" "perlgit"
"perlglossary" "perlgpl" "perlguts" "perlhack" "perlhacktips" "perlhacktut"
"perlhaiku" "perlhist" "perlhpux" "perlhurd" "perlintern" "perlinterp"
"perlintro" "perliol" "perlipc" "perlirix" "perljp" "perlko" "perllexwarn"
"perllinux" "perllocal" "perllocale" "perllol" "perlmacos" "perlmacosx"
"perlmod" "perlmodinstall" "perlmodlib" "perlmodstyle" "perlmpeix"
"perlmroapi" "perlnetware" "perlnewmod" "perlnumber" "perlobj" "perlootut"
"perlop" "perlopenbsd" "perlopentut" "perlos2" "perlos390" "perlos400"
"perlpacktut" "perlperf" "perlplan9" "perlpod" "perlpodspec" "perlpodstyle"
"perlpolicy" "perlport" "perlpragma" "perlqnx" "perlre" "perlreapi"
"perlrebackslash" "perlrecharclass" "perlref" "perlreftut" "perlreguts"
"perlrequick" "perlreref" "perlretut" "perlriscos" "perlrun" "perlsec"
"perlsolaris" "perlsource" "perlstyle" "perlsub" "perlsymbian" "perlsyn"
"perlthrtut" "perltie" "perltoc" "perltodo" "perltooc" "perltoot"
"perltrap" "perltru64" "perltw" "perlunicode" "perlunifaq" "perluniintro"
"perluniprops" "perlunitut" "perlutil" "perluts" "perlvar" "perlvmesa"
"perlvms" "perlvos" "perlwin32" "perlxs" "perlxstut" "perlxstypemap" "re"
"sigtrap" "sort.pod" "strict" "subs" "threads" "threads::shared"
"unicore::Name" "utf8" "vars" "version" "vmsish" "warnings"
"warnings::register"))
