(setq sql-sqlite-program "sqlite3")
(add-to-list 'ac-modes 'sql-interactive-mode)
(setq ac-sources '(ac-source-semantic ac-source-yasnippet))

(add-hook 'sql-interactive-mode-hook '(lambda ()
  (yas/minor-mode)
  (cond
    ((equal 'sql-product "sqlite")
      (sql-send-string ".tables")
    )
    ((equal 'sql-product "postgres")
      (sql-send-string "\dt")
    )
  )
))
