(global-set-key "\M-+" 'enlarge-window)
(global-set-key "\M--" 'shrink-window)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "C-c SPC") 'ace-jump-mode)
;(key-chord-define-global "jj" 'ace-jump-mode)
(global-unset-key "\C-xrs")
(global-set-key "\C-xrs" 'bookmark-save)
(global-unset-key "\C-xrd")
(global-set-key "\C-xrd" 'bookmark-delete)
(global-set-key "\C-xm" 'browse-url-at-point)
(global-set-key (kbd "C-h C-f") 'find-function)
(global-set-key "\C-x\C-k" 'kill-matching-buffers)
(global-set-key "\C-xg" 'grep-mode)
(global-unset-key "\M-,")
(global-set-key "\M-," 'balle-comment-line)
(global-set-key "\t" 'yas-expand)
(global-set-key (kbd "C-d") 'kill-whole-line)
(global-set-key (kbd "M-y") 'browse-kill-ring)
(global-set-key (kbd "M-t") nil) ;; Remove the old keybinding
(global-set-key (kbd "M-t c") 'transpose-chars)
(global-set-key (kbd "M-t C") 'balle-transpose-char-backwards)
(global-set-key (kbd "M-t w") 'transpose-words)
(global-set-key (kbd "M-t W") 'balle-transpose-word-backwards)
(global-set-key (kbd "M-t l") 'transpose-lines)
(global-set-key (kbd "M-t L") 'balle-transpose-line-backwards)
(global-set-key (kbd "M-t e") 'transpose-sexps)
(global-set-key (kbd "M-t s") 'transpose-sentences)
(global-set-key (kbd "M-t p") 'transpose-paragraphs)
(global-set-key (kbd "M-t P") 'balle-transpose-paragraph-backwards)
(global-set-key (kbd "M-t <left>") 'balle-transpose-word-backwards)
(global-set-key (kbd "M-t <right>") 'transpose-words)
(global-set-key (kbd "C-c <left>") 'balle-transpose-word-backwards)
(global-set-key (kbd "C-c <right>") 'transpose-words)
(global-set-key (kbd "M-s") 'balle-search-current-word-in-buffer)
(global-set-key "\C-xU" 'undo)
(global-set-key "\C-x\C-b" 'ibuffer)
(define-key (current-global-map) (kbd "C-x r w") 'window-configuration-to-register)
(global-unset-key "\C-j")
(global-set-key "\C-jb" 'pop-global-mark)
(global-set-key "\C-jc" 'goto-last-change)
(global-set-key "\C-jl" 'ace-jump-line-mode)
(global-set-key "\C-jm" 'pop-global-mark)
(global-set-key "\C-jp" 'forward-paragraph)
(global-set-key "\C-jP" 'backward-paragraph)
(global-set-key "\C-jS" 'balle-goto-prev-whitespace)
(global-set-key "\C-js" 'balle-goto-next-whitespace)
(key-chord-define-global "js" 'balle-goto-next-whitespace)
(key-chord-define-global "jS" 'balle-goto-prev-whitespace)
(global-set-key "\C-jw" 'ace-jump-word-mode)
(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
(global-set-key (kbd "C-j <left>") 'backward-list)
(global-set-key (kbd "C-j <right>") 'forward-list)
(global-set-key (kbd "C-j <up>") 'outline-backward-same-level)
(global-set-key (kbd "C-j <down>") 'outline-forward-same-level)

(global-set-key "\C-cke" 'kmacro-end-or-call-macro)
(global-set-key "\C-ckn" 'kmacro-cycle-ring-next)
(global-set-key "\C-ckp" 'kmacro-cycle-ring-previous)
(global-set-key (kbd "C-c !") 'shell-command-on-buffer-file)
(global-unset-key (kbd "M-!"))
(global-set-key (kbd "M-!") 'shell-command-on-buffer)
(define-key shell-mode-map (kbd "C-x C-o") 'balle-comint-kill-output)
(global-set-key "\C-cte" 'balle-show-emacs-list)
(global-set-key "\C-ctN" 'balle-show-note-list)
(global-set-key "\C-ctr" 'balle-show-read-list)
(global-set-key "\C-ctt" 'balle-show-todo-list)
(global-set-key "\C-ctW" 'balle-show-waiting-list)
(global-set-key "\C-ctx" 'balle-show-next-list)
(global-set-key "\C-ctd" 'balle-show-today-list)
(global-set-key (kbd "M-[ d") 'backward-word)
(global-set-key (kbd "M-[ c") 'forward-word)
(global-set-key (kbd "C-c <up>") 'move-line-up)
(global-set-key (kbd "C-c <down>") 'move-line-down)
(global-set-key (kbd "C-x <up>") 'win-switch-up)
(global-set-key (kbd "C-x <down>") 'win-switch-down)
(global-set-key (kbd "C-x <left>") 'win-switch-left)
(global-set-key (kbd "C-x <right>") 'win-switch-right)

(global-set-key "\C-c\C-u" 'outline-backward-same-level)
(global-set-key "\C-c\C-d" 'outline-forward-same-level)
(global-set-key (kbd "C-c s") 'switch-to-buffer)
(global-set-key (kbd "C-c ;") 'comment-or-uncomment-region)
(global-set-key [f1] 'magit-status)
(global-set-key [f2] 'eww)
;(global-set-key [f3] 'org-agenda)
(global-set-key [f3] 'my-open-calendar)
(global-set-key [f4] 'flycheck-next-error)
(global-set-key [f5] 'flycheck-prev-error)
(global-set-key [f6] 'flyspell-goto-next-error)
(global-set-key [f7] 'balle-flyspell-add-word)
(global-set-key [f8] 'org-capture)
(global-set-key [f9] 'balle-redmine-tickets)
(global-set-key [f10] 'balle-projectile-open-all-recent)
