language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
# Bootstrap Puppet, and install our Puppet modules
before_install:
  - sh ./puppet/bootstrap.sh
  - gem install puppet librarian-puppet
  - librarian-puppet install
# Call Puppet to bootstrap the testing environment and install test
# requirements.  We install Ruby tools separately as non-root user to avoid
# screwing up with RVM.  We pass --debug to prevent Travis from getting stuck
# due to no output, and to get as good error messages as possible
install:
  - sudo FACTER_travis=true puppet apply --debug --modulepath=./puppet/lib:./puppet/modules ./puppet/manifests/site.pp
  - puppet apply --debug --modulepath=./puppet/lib:./puppet/modules ./puppet/manifests/travis.pp
  - make packages
# Build documentation and run unit tests
script:
  - make -k info test
